### ISSUE TITLE
can not reproduce the result of widerface with your model 

### ISSUE THREAD

**Issue by tranorrepository** [liuwei16/CSP#12]
I used the code test_wider_ms.py and your model, but the widerface result are easy 81.2%, medium 82.2%, hard 75.3%.

**Comment by liuwei16** [comment]
Sorry. There was an error in line 101-102 in  the original keras_csp/bbox_process.py, thus test_wider_ms.py is not able to run successfully.
 Code is updated, which runs OK under Keras 2.0.6

**Comment by hdjsjyl** [comment]
@liuwei16   Does it have the same influence about test_city? Thanks
