### ISSUE TITLE
sorry to bother you. I encountered this problem when testing the h+w(model_CSP/caltech/fromimgnet/h+w/) model with test_caltech.py, which was encountered when loading hdf5 with model.load_weights(weight1, by_name=True). Do you know the reason?

### ISSUE THREAD

**Issue by xncaffe** [liuwei16/CSP#18]
sorry to bother you. I encountered this problem when testing the h+w(model_CSP/caltech/fromimgnet/h+w/) model with “test_caltech.py”, which was encountered when loading hdf5 with ”model.load_weights(weight1, by_name=True)“. Do you know the reason?

**Comment by DRAEYE** [comment]
Hello, excuse me, I have come across the same problem, how did you deal with it at end?
