### ISSUE TITLE
Performance of the CSP detector

### ISSUE THREAD

**Issue by lwpyr** [liuwei16/CSP#21]
I directly use the weights you provided which is trained on CityPersons, However, when I test the detector on my own picture, its performance is even worse than my coarsely trained FPN, many overlapped cases cannot be handled properly. So how is the problem generated? I strictly obey the pre/post-process of the input/output. So any idea of the inference in deploy? Thanks!
And the detector also shares the same drawback with other single-stage detectors which is the bounding box is not well fit to the target. Actually, the results of CSP give me an impression as it is generated by Yolo or SSD.
By the way, I also think the idea of heights regression is very original.

**Comment by xncaffe** [comment]
The results of my test are acceptable. Have you set score_threshold?

**Comment by lwpyr** [comment]
I mean, I test the model on the real scene, which is an application I am currently working on. The result is not so good when partial overlap happens.
