### ISSUE TITLE
Pretrained models at Baidu Yan

### ISSUE THREAD

**Issue by lasuomela** [liuwei16/CSP#27]
Hello @liuwei16, thank you for the excellent work!

I'm trying to reproduce your results from the paper, and would like to try out the parameters you have uploaded to Baidu. However, downloading from Baidu from outside China seems to be almost impossible, and I haven't been able to obtain the files.

Would it be possible for you to host the network weight files somewhere else than Baidu?

Best regards!

**Comment by liuwei16** [comment]
sorry, I have already uploaded them to Google Drive. Here is the link,
https://drive.google.com/drive/folders/1W52Uv2r1CXsLYDV4Dzpb-urPEDoWOG__?usp=sharing

**Comment by lasuomela** [comment]
Okay, thank you very much!
