### ISSUE TITLE
There is a bug in the Caltech dataset preparation!

### ISSUE THREAD

**Issue by TachibanaYoshino** [liuwei16/CSP#28]
Use matlab to run the extract_img_anno.m.
>> extract_img_anno
Undefined function or variable 'dbExtract'。

**Comment by bomtorazek** [comment]
http://www.vision.caltech.edu/Image_Datasets/CaltechPedestrians/

**Comment by bomtorazek** [comment]
Piotr's Matlab Toolbox, Matlab evaluation/labeling code (3.2.1)
