### ISSUE TITLE
how can i view the result image with bounding boxes?

### ISSUE THREAD

**Issue by lookdeceline** [liuwei16/CSP#48]
I am currently working on Caltech dataset, and have completed upto the evaluation stage by running ./eval_caltech/dbEval.m file. I have gotten  the eval-newReasonable.txt  file as well.
The question is, where and how can I view the final image with bounding boxes?
Please help.
Thanks!!

**Comment by bomtorazek** [comment]
You can use the toolbox from Caltech.
If you run dbBrowser.m with modification of directory, you can get images with annotations.

**Comment by CConory** [comment]
use test_caltech.py and add cv2.rectangle to write the bounding boxes on the image when get the boxes

**Comment by Boisa** [comment]
> 您可以使用加州理工学院的工具箱。
> 如果在修改目录的情况下运行dbBrowser.m，则可以获得带批注的图像。



> You can use the toolbox from Caltech.
> If you run dbBrowser.m with modification of directory, you can get images with annotations.

Can you elaborate on that? How to modify the directory? thanks

**Comment by bomtorazek** [comment]
> > 您可以使用加州理工学院的工具箱。
> > 如果在修改目录的情况下运行dbBrowser.m，则可以获得带批注的图像。
> 
> > You can use the toolbox from Caltech.
> > If you run dbBrowser.m with modification of directory, you can get images with annotations.
> 
> Can you elaborate on that? How to modify the directory? thanks


 Yes, I elaborated on it.
I did like below. I used Kaist dataset rather than caltech.
[pth,sIds,vIds,skip] = dbInfo; % '/home/eungyo/CSP/eval_caltech/data-USA'
pth2 = '/home/eungyo/CSP/output/valresults/kaist/h/off';
% 0 ...  6 7 8 9 10 11 > sIds. set  skip =20
%rPth=[pth '/res/ChnFtrs'];    % directory containing results
%rPth=[pth '/res/082+city+0.1+VI+512'];
rPth = [pth2 '/082+city+0.1+LWIR+e117'];

**Comment by Boisa** [comment]
Thank you very much for your enthusiastic answer，it is good for me. I also have used the KAIST.We only have one ground truth file named gt-Reasonable.mat. （1）When we evelute caltech, do you only get one MR for reasonable? Do we need to submit detector results to Piotr Dollár？（2）Another question，where are you setting iou=0.75？
I sincerely hope that receive your answer,extremely grateful!

**Comment by Boisa** [comment]
Thank you very much for your enthusiastic answer，it is good for me. For caltech,we only have one ground truth file named gt-Reasonable.mat. （1）Do you only get one MR for reasonable? Do we need to submit detector results to Piotr Dollár？（2）Another question，where are you setting iou=0.75？
I sincerely hope that receive your answer,extremely grateful!

**Comment by bomtorazek** [comment]
> Thank you very much for your enthusiastic answer，it is good for me. For caltech,we only have one ground truth file named gt-Reasonable.mat. （1）Do you only get one MR for reasonable? Do we need to submit detector results to Piotr Dollár？（2）Another question，where are you setting iou=0.75？
> I sincerely hope that receive your answer,extremely grateful!

(1) That is the problem. I think there will be codes for generating gt file. I had plans for generating other gts, but nowadays I am not working on pedestrian detection due to my professor. Thus, I have no ideas sorry. In the paper, the author used other gts, such as occluded, so there must be a way. (2) I think it was vbb if I remember correctly.

**Comment by Boisa** [comment]
I am very glad to communicate with you. Thank you for your answer .

**Comment by Boisa** [comment]
> > 非常感谢您的热情回答，对我有好处。对于Caltech，我们只有一个名为gt-Reasonable.mat的地面真实文件。（1）您只得到一份合理的MR吗？我们是否需要将检测器结果提交给PiotrDollár？（2）另一个问题，您将iou = 0.75设置在哪里？
> > 我衷心希望收到您的答复，万分感谢！
> 
> （1）这就是问题所在。我认为会有用于生成gt文件的代码。我曾计划生成其他GTS，但是由于我的教授，如今我不从事行人检测。因此，对不起我没有想法。在本文中，作者使用了其他gts（例如遮挡），因此必须有一种方法。（2）如果我没记错的话，我认为是vbb。

hello,I can't find the place to set the iou=0.5/0.75,can you describe it in detail?thank you.

**Comment by vickyliuliu** [comment]
Hello, I'm also trying to visualize the results for test_caltech. However, I do not understand the Information in the .txt files, and the author didn't explain. Do you know what the contents mean?  Thannks~

**Comment by lhs21** [comment]
> use test_caltech.py and add cv2.rectangle to write the bounding boxes on the image when get the boxes

hello，i have write the code which can draw bb on the image ,i follow the .txt file that got in result(output/valresutlts/caltech/h/off),but I find there are too many bounding boxes, which is not right ,can you tell me where you get the right bounding boxes' data?
![set06V0001049](https://user-images.githubusercontent.com/27982354/112984459-7be7b400-9191-11eb-971d-4934e2dc5866.jpg)
