### ISSUE TITLE
How to compile NMS module?

### ISSUE THREAD

**Issue by Brizel** [liuwei16/CSP#49]
I tried this code on Python3.5 and the training process has already been done.
But when I test the model, I can't pass through nms.
I found that this part is built on Cython but I have no idea about it.
Does anybody know how to compile this part?

**Comment by MessyPaste** [comment]
run:python setup.py build_ext --inplace

**Comment by bomtorazek** [comment]
https://github.com/rbgirshick/py-faster-rcnn
You can check this link.
You need utils (a folder), Makefile, and setup.py from the link, and follow step 3.

**Comment by bomtorazek** [comment]
Oh one more, you need to install cython using command.

**Comment by fengyuentau** [comment]
https://github.com/liuwei16/CSP/issues/9#issuecomment-542024814 follow this comment to compile nms module.
