### ISSUE TITLE
How come RTX 2080 Ti is working for only the batch size smaller than 4?

### ISSUE THREAD

**Issue by bomtorazek** [liuwei16/CSP#56]
In the paper, they said they used 16 images per batch for Caltech with only one GTX 1080 Ti.
I am using one RTX 2080 Ti and set the batch size as 2, which is 8 times smaller than that of the paper's, because setting the batch size more than 2 causes OOM.

I cannot understand that my GPU causes OOM with the batch size of 4, cause it is 2 times better than GTX 1080 Ti.
Also, it takes about 600s to train only one epoch.

I am using Ubuntu 18.04, python 2.7, CUDA 8.0, and CUDNN 6.0 with anaconda virtual environment.
RTX 2080 Ti, 32GB RAM, AMD Ryzen 5 3600.

Am I missing something? I am a newbie, so I welcome you to advise anything to me.

**Comment by bomtorazek** [comment]
I figured out that it is natural considering specs from computers in other issues. I think that the authors might use 4 parallel GTX 1080 Ti for training.

**Comment by fyture** [comment]
I got the same problem. when setting batchsize 16 on one 2080ti causes OOM. So I have to put 8 on each GPU. And also, while training, my GPU memory are full. But the use of GPU is 0%, I dont know what i am missing. Could you share me with some advices? Thank you very much.
