### ISSUE TITLE
Dimensions must be equal, but are 256 and 84 for 'P3norm_7/mul' 

### ISSUE THREAD

**Issue by Abel150** [liuwei16/CSP#76]
When I run the train_caltech.py, the error shows the "Dimensions must be equal, but are 256 and 84 for 'P3norm_7/mul' (op: 'Mul') with input shapes: [?,?,?,256], [84]". I will be glad if you know the reason and help me with the code.

**Comment by quhb2455** [comment]
@Abel150 
I am so sorry that i reply to your closed issue
i met same problem. if you know how to solve it, can you let me know that?
